[package]
name = "bindereh"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
regex = "1.11.1"
tokio = { version = "1.46.1", features = ["full"] }
rayon = "1.8"
shared_types = { path = "../shared_types" }
futures = "0.3.31"

[dev-dependencies]
tempfile = "3.8"
