[package]
name = "shared_types"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }