[package]
name = "bambang"
version = "0.1.0"
edition = "2024"

[dependencies]
bindereh = { path = "../bindereh" }
matan = { path = "../matan" }
pambudi = { path = "../pambudi" }
tokio = { version = "1.46.1", features = ["full"] }
